CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS customer_db;
CREATE DATABASE IF NOT EXISTS staff_db;

GRANT ALL PRIVILEGES ON auth_db.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON customer_db.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON staff_db.* TO 'root'@'%';
FLUSH PRIVILEGES;
